# Generated by Django 3.2.3 on 2021-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210618_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
    ]
